include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    only_throw_errors: false
