name: query_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  postgres: 2.5.2

dev_dependencies:
  very_good_analysis: ^3.1.0
  test: ^1.16.0
